/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.schoolmarket.gui;

import com.mycompany.schoolmarket.boundary.SchoolMarket;
import com.mycompany.schoolmarket.control.Store;
import com.mycompany.schoolmarket.entity.Book;
import com.mycompany.schoolmarket.entity.BookCondition;
import com.mycompany.schoolmarket.entity.Student;
import com.mycompany.schoolmarket.entity.StudentClass;
import com.mycompany.schoolmarket.entity.Subject;
import com.mysql.cj.x.protobuf.MysqlxDatatypes.Array;

import java.math.BigDecimal;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JTable;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author utentepc
 */
public class WinSchoolMarket extends javax.swing.JFrame {

    ArrayList<Integer> listIdStudents = new ArrayList<>();
    /**
     * Creates new form WinSchoolMarket
     */
    public WinSchoolMarket() {
        initComponents();
        refreshListClass();
        refreshListStudents();
        refreshListClassBooks();
        refreshListSubjects();
        //refreshTableBooks();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_booksList = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tx_firstName = new javax.swing.JTextField();
        tx_lastName = new javax.swing.JTextField();
        tx_age = new javax.swing.JTextField();
        btInsertStudentSubscription = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tx_bookName = new javax.swing.JTextField();
        sp_bookCost = new javax.swing.JSpinner();
        lb_logMessage = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tp_showStudent = new javax.swing.JTextPane();
        btInsertBook = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        tx_email = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        lst_studentsList = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        tx_bookHealth = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst_classesList = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        lst_classesBook = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        lst_subjects = new javax.swing.JList<>();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SCHOOL MARKET");

        tb_booksList.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "nome", "classe", "costo", "grado", "quantity"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane2.setViewportView(tb_booksList);

        jLabel2.setText("Inserisci i tuoi dati nelle caselle sottostanti per registrarti nel e-commerce!");

        jLabel3.setText("INSERIRE I DATI DEL NUOVO STUDENTE :");

        jLabel4.setText("Nome : ");

        jLabel5.setText("Cognome :");

        jLabel6.setText("Età : ");

        jLabel7.setText("Sezione classe :");

        tx_firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_firstNameActionPerformed(evt);
            }
        });

        btInsertStudentSubscription.setText("OKAY");
        btInsertStudentSubscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsertStudentSubscriptionActionPerformed(evt);
            }
        });

        jLabel8.setText("INSERIRE I DATI DEL NUOVO LIBRO:");

        jLabel9.setText("Nome libro :");

        jLabel10.setText("Costo :");

        jLabel11.setText("Classe :");

        tx_bookName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tx_bookNameActionPerformed(evt);
            }
        });

        lb_logMessage.setText("nessun dato ancora fornito...");

        jScrollPane3.setViewportView(tp_showStudent);

        btInsertBook.setText("OKAY");
        btInsertBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsertBookActionPerformed(evt);
            }
        });

        jLabel12.setText("E-mail : ");

        lst_studentsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lst_studentsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                if(!evt.getValueIsAdjusting()){
                        lst_studentsListValueChanged(evt);
                }
            }
        });
        jScrollPane4.setViewportView(lst_studentsList);

        jLabel13.setText("Stato dell'oggetto :");

        jLabel14.setText("(es. Grado A, B o C)");

        lst_classesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lst_classesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lst_classesListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lst_classesList);

        lst_classesBook.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lst_classesBook.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lst_classesBookValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(lst_classesBook);

        jLabel15.setText("LISTA LIBRI");

        jLabel16.setText("Sei nuovo? ");

        jLabel17.setText("Premi il pulsante \"OKAY\" ");

        jLabel18.setText("per aggiungere il libro.");

        jLabel19.setText("Vuoi vendere un libro?");

        jLabel20.setText("Compila i dati sottostanti per aggiungerlo nel catalogo!");

        jLabel21.setText("Materia :");

        lst_subjects.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lst_subjects.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lst_subjectsValueChanged(evt);
            }
        });
        jScrollPane6.setViewportView(lst_subjects);

        jLabel22.setText("Premi \"OKAY\" per completare");

        jLabel23.setText("la registrazione");

        jLabel24.setText("SELEZIONARE ACCOUNT ESISTENTE : ");

        jLabel25.setText("Se invece ti sei già registrato/a puoi scegliere tra gli utenti esistenti : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel19)
                                                                        .addComponent(jLabel20))
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel3)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                layout.createSequentialGroup()
                                                                                                        .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                .addComponent(
                                                                                                                        jLabel5,
                                                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(
                                                                                                                        jLabel4,
                                                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(
                                                                                                                        jLabel6,
                                                                                                                        javax.swing.GroupLayout.Alignment.LEADING))
                                                                                                        .addGap(21, 21,
                                                                                                                21))
                                                                                        .addGroup(layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel12)
                                                                                                .addGap(33, 33, 33)))
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                        false)
                                                                                        .addGroup(layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(layout
                                                                                                        .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                false)
                                                                                                        .addComponent(
                                                                                                                tx_firstName)
                                                                                                        .addComponent(
                                                                                                                tx_lastName,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                124,
                                                                                                                Short.MAX_VALUE)
                                                                                                        .addComponent(
                                                                                                                tx_age))
                                                                                                .addGap(23, 23, 23)
                                                                                                .addComponent(jLabel7)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(
                                                                                                        jScrollPane1,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        80,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addGroup(layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(tx_email,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        126,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                        41,
                                                                                                        Short.MAX_VALUE)
                                                                                                .addGroup(layout
                                                                                                        .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                        .addComponent(
                                                                                                                jLabel22)
                                                                                                        .addComponent(
                                                                                                                btInsertStudentSubscription)
                                                                                                        .addComponent(
                                                                                                                jLabel23)))))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(8, 8, 8)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                                        false)
                                                                                        .addGroup(layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(layout
                                                                                                        .createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                false)
                                                                                                        .addGroup(layout
                                                                                                                .createSequentialGroup()
                                                                                                                .addComponent(
                                                                                                                        jScrollPane6,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                        142,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addPreferredGap(
                                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                .addComponent(
                                                                                                                        jScrollPane5,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                        60,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                        .addComponent(
                                                                                                                jLabel9)
                                                                                                        .addComponent(
                                                                                                                tx_bookName))
                                                                                                .addGap(24, 24, 24))
                                                                                        .addGroup(layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel21)
                                                                                                .addPreferredGap(
                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                        Short.MAX_VALUE)
                                                                                                .addComponent(jLabel11,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        72,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel10)
                                                                                        .addComponent(sp_bookCost,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                120,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addGroup(layout
                                                                                                .createParallelGroup(
                                                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                        false)
                                                                                                .addComponent(jLabel14,
                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                        Short.MAX_VALUE)
                                                                                                .addComponent(jLabel13)
                                                                                                .addComponent(
                                                                                                        tx_bookHealth,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        102,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addComponent(jLabel17)
                                                                                        .addComponent(jLabel18)
                                                                                        .addComponent(btInsertBook)))
                                                                        .addComponent(jLabel8))
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(107, 107, 107)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jScrollPane2)
                                                                                        .addGroup(layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel15,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        85,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(0, 0,
                                                                                                        Short.MAX_VALUE))))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(101, 101, 101)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel24,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                        .addGroup(layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel25)
                                                                                                .addGap(0, 0,
                                                                                                        Short.MAX_VALUE))
                                                                                        .addGroup(
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                layout.createSequentialGroup()
                                                                                                        .addComponent(
                                                                                                                jScrollPane4,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                272,
                                                                                                                Short.MAX_VALUE)
                                                                                                        .addGap(18, 18,
                                                                                                                18)
                                                                                                        .addComponent(
                                                                                                                jScrollPane3,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                226,
                                                                                                                Short.MAX_VALUE))
                                                                                        .addGroup(layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(6, 6, 6)
                                                                                                .addComponent(
                                                                                                        lb_logMessage,
                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                        Short.MAX_VALUE))))))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(414, 414, 414)
                                                                .addComponent(jLabel1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 113,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel16))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel2,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 458,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, 1037, Short.MAX_VALUE))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel25))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel24))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane3)
                                        .addComponent(jScrollPane4)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel4,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        26,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                        .addComponent(jLabel5,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                22,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(tx_lastName,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                .addComponent(tx_firstName,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(jLabel7,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        21,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel6,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                21,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(tx_age,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(jScrollPane1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 0,
                                                                Short.MAX_VALUE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel12,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                20,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(tx_email,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel22)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(jLabel23)))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(69, 69, 69)
                                                .addComponent(jLabel19)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel20)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(23, 23, 23)
                                                                .addComponent(jLabel15)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jScrollPane2,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 266,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(17, 17, 17)
                                                                .addComponent(jLabel8)
                                                                .addGap(10, 10, 10)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel9)
                                                                        .addComponent(jLabel10))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(sp_bookCost,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(tx_bookName,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(12, 12, 12)
                                                                .addComponent(jLabel13)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel14)
                                                                        .addComponent(jLabel11)
                                                                        .addComponent(jLabel21,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                10,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(tx_bookHealth,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jLabel17)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jLabel18)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(btInsertBook,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        42,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                        .addComponent(jScrollPane6)
                                                                        .addComponent(jScrollPane5))))
                                                .addGap(29, 29, 29))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lb_logMessage,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 16,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btInsertStudentSubscription))
                                                .addGap(26, 26, 26)
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE)))));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tx_firstNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tx_firstNameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_tx_firstNameActionPerformed

    private void btInsertStudentSubscriptionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btInsertStudentSubscriptionActionPerformed
        // TODO add your handling code here:

        String newStudent = "Le credenziali del nuovo studente sono: \n";
        String firstName = tx_firstName.getText();
        String lastName = tx_lastName.getText();
        String email = tx_email.getText();
        String age = tx_age.getText();
        int ageNum = Integer.parseInt(age);

        StudentClass ci = Store.getClassIndex(lst_classesList.getSelectedIndex());
        Student str = SchoolMarket.studentRegistration(firstName, lastName, ageNum, email, null, ci);
        newStudent += str.toString();
        System.out.println(newStudent);
        newStudent = tp_showStudent.getText() + "\n" + newStudent;
        tp_showStudent.setText(newStudent);

        tx_firstName.setText("");
        tx_lastName.setText("");
        tx_age.setText("");
        tx_email.setText("");

        lb_logMessage.setText("Studente aggiunto con successo!");

    }// GEN-LAST:event_btInsertStudentSubscriptionActionPerformed

    private void lst_studentsListValueChanged(javax.swing.event.ListSelectionEvent evt) {// GEN-FIRST:event_lst_studentsListValueChanged
        // TODO add your handling code here:
        
        String firstname = lst_studentsList.getSelectedValue().getFname();
        String lastname = lst_studentsList.getSelectedValue().getLname();
        String name = lastname + " " + firstname;

        int classSection = lst_studentsList.getSelectedValue().getClassSection().getIdClass();
        lb_logMessage.setText(" STUDENT_NAME: " + name + " " + "CLASS_SECTION: " + classSection);
        refreshTableBooks();
    }// GEN-LAST:event_lst_studentsListValueChanged

    private void btInsertBookActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btInsertBookActionPerformed
        // TODO add your handling code here:

        String newBook = "Le credenziali del nuovo libro sono: \n";
        String bookName = tx_bookName.getText();
        BigDecimal cost = BigDecimal.valueOf((double) sp_bookCost.getValue()) ;
        BookCondition bci = Store.getBookConditionIndex(tx_bookHealth.getText());
        Student sti = Store.getStudentIndex(lst_studentsList.getSelectedValue().getIdStudent());
        StudentClass ci1 = Store.getClassIndex(lst_classesBook.getSelectedValue().getIdClass());
        Subject sbi = Store.getSubjectIndex(lst_subjects.getSelectedValue().getIdSubject());
        
        Book bv = SchoolMarket.bookVending(bookName, cost, bci, sti, ci1, sbi);
        refreshTableBooks();
        newBook += bv.toString();
        System.out.println(newBook);
        newBook = tp_showStudent.getText() + "\n" + newBook;
        tp_showStudent.setText(newBook);

        tx_bookName.setText("");
        tx_bookHealth.setText("");
        sp_bookCost.setValue(0);

        lb_logMessage.setText("Libro aggiunto con successo!");

    }// GEN-LAST:event_btInsertBookActionPerformed

    private void lst_classesListValueChanged(javax.swing.event.ListSelectionEvent evt) {// GEN-FIRST:event_lst_classesListValueChanged

        // TODO add your handling code here:
        // int index = lst_classesList.getSelectedIndex();
        String section = lst_classesList.getSelectedValue().getSection();
        int classId = lst_classesList.getSelectedValue().getIdClass();
        lb_logMessage.setText("CLASS_ID: " + classId + " SECTION: " + section);
    }// GEN-LAST:event_lst_classesListValueChanged

    private void tx_bookNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tx_bookNameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_tx_bookNameActionPerformed

    private void lst_classesBookValueChanged(javax.swing.event.ListSelectionEvent evt) {// GEN-FIRST:event_lst_classesBookValueChanged
        // TODO add your handling code here:
        // int index = lst_classesBook.getSelectedIndex();
        String section = lst_classesBook.getSelectedValue().getSection();
        int classId = lst_classesBook.getSelectedValue().getIdClass();
        lb_logMessage.setText("CLASS_ID: " + classId + " SECTION: " + section);
    }// GEN-LAST:event_lst_classesBookValueChanged

    private void lst_subjectsValueChanged(javax.swing.event.ListSelectionEvent evt) {// GEN-FIRST:event_lst_subjectsValueChanged
        // TODO add your handling code here:
        // int index = lst_subjects.getSelectedIndex();
        String subject = lst_subjects.getSelectedValue().getSubjectName();
        // int classId = lst_subjects.getSelectedValue().getIdSubject();
        lb_logMessage.setText("SUBJECT: " + subject);

    }// GEN-LAST:event_lst_subjectsValueChanged

    public void refreshListClass() {

        List<StudentClass> result = SchoolMarket.classesList();
        DefaultListModel<StudentClass> model = new DefaultListModel<>();
        result.forEach(v -> model.addElement(v));
        lst_classesList.setModel(model);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinSchoolMarket.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinSchoolMarket.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinSchoolMarket.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinSchoolMarket.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinSchoolMarket().setVisible(true);
            }
        });
    }

    public void refreshListStudents() {

        List<Student> result = SchoolMarket.studentsList();
        DefaultListModel<Student> model = new DefaultListModel<>();
        //result.forEach(v -> model.addElement(v));
        for (Student student : result) {
                model.addElement(student);
                listIdStudents.add(student.getIdStudent());
        }
        lst_studentsList.setModel(model);

    }

    private void refreshListClassBooks() {

        List<StudentClass> result = SchoolMarket.classesList();
        DefaultListModel<StudentClass> model = new DefaultListModel<>();
        result.forEach(v -> model.addElement(v));
        lst_classesBook.setModel(model);

    }

    private void refreshTableBooks() {

        
        int index = lst_studentsList.getSelectedIndex();
        int idstSelected = listIdStudents.get(index);
        List<Book> booksByUser = SchoolMarket.booksByUser(idstSelected);
        DefaultTableModel model = (DefaultTableModel) tb_booksList.getModel();
        DefaultTableModel dm = (DefaultTableModel) tb_booksList.getModel();

        while (model.getRowCount() > 0) {
                model.removeRow(0);
        }

        for (Book b : booksByUser) {
                String bn = b.getBookName().toString();
                String cs = b.getClassSection().toString();
                String co = b.getCost().toString();
                String gr = b.getGrade().toString();
                Object[] obj = new Object[]{
                        bn, cs, co, gr
                };
                model.addRow(obj);
        }
        tb_booksList.setModel(model);

        /*try {
            conn = DriverManager.getConnection(DB_URL, USER, PASS);
            PreparedStatement stmt = conn.prepareStatement("SELECT tb.book_name, tc.section, tb.cost, tb.grade, count(tb.id_subject) as quantity " +
                                                           "FROM t_books as tb " +
                                                           "join t_subjects tsu on tsu.id_subjects = tb.id_subject " +
                                                           "join t_classes tc on tc.id_class = tb.id_class " +
                                                           "group by tb.id_subject, tb.grade, tb.id_class, tc.section, tb.book_name, tb.cost " +
                                                           "order by tc.section");
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tb_booksList.getModel();
            
            DefaultTableModel dm = (DefaultTableModel)tb_booksList.getModel();

            while(dm.getRowCount() > 0)
            {
                dm.removeRow(0);
            }

            while (rs.next()) {
                String tb = rs.getString("tb.book_name");
                String cl = rs.getString("tc.section");
                String gr = rs.getString("tb.grade");
                int co = rs.getInt("tb.cost");
                int qua = rs.getInt("quantity");
            Object[] obj = new Object[]{
                tb,cl,co,gr,qua
            };
            model.addRow(obj);
                
            }
            tb_booksList.setModel(model);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }*/
    
    }

    private void refreshListSubjects() {

        List<Subject> result = SchoolMarket.subjectList();
        DefaultListModel<Subject> model = new DefaultListModel<>();
        result.forEach(v -> model.addElement(v));
        lst_subjects.setModel(model);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btInsertBook;
    private javax.swing.JButton btInsertStudentSubscription;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb_logMessage;
    private javax.swing.JList<StudentClass> lst_classesBook;
    private javax.swing.JList<StudentClass> lst_classesList;
    private javax.swing.JList<Student> lst_studentsList;
    private javax.swing.JList<Subject> lst_subjects;
    private javax.swing.JSpinner sp_bookCost;
    private javax.swing.JTable tb_booksList;
    private javax.swing.JTextPane tp_showStudent;
    private javax.swing.JTextField tx_age;
    private javax.swing.JTextField tx_bookHealth;
    private javax.swing.JTextField tx_bookName;
    private javax.swing.JTextField tx_email;
    private javax.swing.JTextField tx_firstName;
    private javax.swing.JTextField tx_lastName;
    // End of variables declaration//GEN-END:variables

}
